- name: configure nodejs repo
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: install nodejs
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: add application user
  ansible.builtin.user:
    name: roboshop

- name: remove old app content
  ansible.builtin.file:
    path: /app
    state: absent

- name: create app document directory
  ansible.builtin.file:
     path: /app
     state: directory

- name: download catalogue app content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/catalogue.zip
    dest: /app
    remote_src: yes

- name: Install Nodejs dependencies
  community.general.npm:
     path: /app
     state: latest

- name: SystemD Setup
  ansible.builtin.copy:
     src: catalogue.servicefile
     dest: /etc/systemd/system/catalogue.service


- name: Start catalogue service
  ansible.builtin.systemd:
      name: catalogue
      daemon_reload: yes
      enabled: yes
      state: restarted

- name: install mongodb server
  ansible.builtin.yum:
    name: mongodb-org-shel
    state: installed


- name: Load Schema
  community.mongodb.mongodb_shell:
    login_host: mongodb-dev.devopsm26.online
    file: "/app/schema/catalogue.js"
    idempotent: yes

